name: Build and Publish
permissions:
  contents: write

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all history for branch creation

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build mod
        run: ./gradlew build

      - name: Generate version and patch files
        run: ./gradlew generateUpdateFiles

      - name: Commit update files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Checkout or create the update branch
          if git show-ref --verify --quiet refs/heads/auto/update-version; then
            git checkout auto/update-version
          else
            git checkout -b auto/update-version
          fi

          # Stage files
          git add version/version.json version/patch.json

          # Commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Update version and patch info for ${{ github.sha }}"
            git push -u origin auto/update-version
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
